site_name: Warmo's Stuff
theme:
    name: material
    language: en
    palette:
        scheme: slate
        primary: red
    features:
        navigation.instant
        navigation.instant.progress
        navigation.tracking
plugins:
    - blog:
        categories: false
    - search
    - git-latest-changes
    - git-revision-date-localized
    - open-in-new-tab
    - awesome-pages
markdown_extensions:
    - pymdownx.keys
    - pymdownx.smartsymbols
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/MrWarmo"  target="_blank" rel="noopener">Jake W</a>