site_name: Warmo's Stuff
theme:
    name: material
    language: en
    palette:
        scheme: slate
        primary: red
    features:
        navigation.instant
        navigation.instant.progress
        navigation.tracking
plugins:
    - blog:
        categories: false
    - search
markdown_extensions:
    - pymdownx.keys
    - pymdownx.smartsymbols
    - attr_list
    - md_in_html
copyright: |
  &copy; 2024 <a href="https://github.com/MrWarmo"  target="_blank" rel="noopener">Jake W</a>